import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full flex justify-center py-6 gap-6 bg-[#fffbe6] border-b border-yellow-300 text-lg font-semibold shadow-sm">
          <a href="/" className="hover:text-yellow-700">Home</a>
          <a href="/shop" className="hover:text-yellow-700">Shop</a>
          <a href="/blog" className="hover:text-yellow-700">Blog</a>
          <a href="/coach" className="hover:text-yellow-700">Coach</a>
          <a href="/video-store" className="hover:text-yellow-700">Video Store</a>
          <a href="/products" className="hover:text-yellow-700">Products</a>
          <a href="/healing-technology" className="hover:text-yellow-700">Healing Technology</a>
          <a href="/about" className="hover:text-yellow-700">About</a>
          <a href="/contact" className="hover:text-yellow-700">Contact</a>
        </nav>
        {children}
      </body>
    </html>
  );
}
